name: Pull Request Create Runner

on:
  #push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build ci image
        run: |
          #env
          docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}
          docker buildx bake --push --file docker-bake.hcl --file docker-bake.ci.hcl default
