name: Pull Request Create Runner

on:
  #push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ci image
        run: |
          env
          echo Running CI job
