name: Pull Request Create Runner

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry.owns.com
        uses: docker/login-action@v3
        with:
          registry: registry.owns.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build ci image
        run: |
          export GITHUB_PR=${{ github.event.pull_request.number }}
          docker buildx bake --push --file docker-bake.hcl --file docker-bake.ci.hcl default
