name: PR Merge Runner
on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_API_TOKEN }}

  build:
    needs: release

    runs-on: ubuntu-latest
    steps:
      - name: Load docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry.owns.com
        uses: docker/login-action@v3
        with:
          registry: registry.owns.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy image
        run: |
          VERSION=$(jq -r '.release.version' <<< "${{ steps.semantic.outputs.release }}")
          docker buildx bake --push --file docker-bake.hcl --file docker-bake.build.hcl default
